### PR TITLE
[RFR] Upgrade to node 7

### PR DESCRIPTION
**Pull request by djhi**
- [x] Upgraded to node 7
- [x] Updated all dependencies
- [x] Removed dependency to async-to-gen

### CODE REVIEW

**Review by Kmaschta — APPROVED** [review]
NodeJS move faster than Travis update its doc! https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Available-Versions

**Comment by djhi** [comment]
And yet, node 7 is available on travis ^^

**Comment by djhi** [comment]
Can't make the npm install work... I don't know why yet

**Comment by Kmaschta** [comment]
Have you tried yarn? :p

**Comment by djhi** [comment]
ah well: https://github.com/mapbox/node-sqlite3/issues/728

**Comment by djhi** [comment]
Closed in favor of #132

**Pull request closed without merging**
