### PR TITLE
[RFR] Add configuration for rateLimiter

### PR DESCRIPTION
**Pull request by alexisjanvier**
Sometimes it generates `429` errors during api functional tests.

### CODE REVIEW

**Comment by djhi** [comment]
It's because you didn't updated your test config.

**Comment by djhi** [comment]
@Kmaschta updated the `test.js-dist` for this

**Comment by Kmaschta** [comment]
And IMO, it's preferable to not import config into the rate limiter, you can simply check if userOptions is false.

**Comment by alexisjanvier** [comment]
ok, ok :)

**Pull request closed without merging**
