### PR TITLE
[RFR] Moved e2e tests inside their applications directory

### PR DESCRIPTION
**Pull request by djhi**
- [x] Renamed `isomorphic` to `common`
- [x] Moved e2e tests inside their applications directory

### CODE REVIEW

**Comment by fzaninotto** [comment]
needs rebase

**Comment by fzaninotto** [comment]
we have a `src` inside a `src` ? I'm not fond of that. Any alternative?

**Comment by djhi** [comment]
@fzaninotto any suggestions ?

**Comment by djhi** [comment]
As discussed, e2e fodlers have been moved at the app level

**Comment by alexisjanvier** [comment]
:+1:

**Pull request merged**
